// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRE5Uhkb1IcORIf5cJYtD5_GHuKWH0kPE',
    appId: '1:939745556996:web:f92fe97e818df5dd531351',
    messagingSenderId: '939745556996',
    projectId: 'dlgrijpah7jlvfjuexnmcmv4p0rmbc',
    authDomain: 'dlgrijpah7jlvfjuexnmcmv4p0rmbc.firebaseapp.com',
    storageBucket: 'dlgrijpah7jlvfjuexnmcmv4p0rmbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcq-1vzx75UkT750k1XA-hSz68K2v3Fdc',
    appId: '1:939745556996:ios:4833fb140a01da6e531351',
    messagingSenderId: '939745556996',
    projectId: 'dlgrijpah7jlvfjuexnmcmv4p0rmbc',
    storageBucket: 'dlgrijpah7jlvfjuexnmcmv4p0rmbc.firebasestorage.app',
    androidClientId: '939745556996-ttp4caunivrq1j5e91jl5nrhu1icl1cl.apps.googleusercontent.com',
    iosClientId: '939745556996-e5m5tm420e6qptnnltadd67vn2hi71ph.apps.googleusercontent.com',
    iosBundleId: 'com.cakeaide.cakeaideapp2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCx72OZXB_xREZURD7P_R5FDQBbkhXoHc',
    appId: '1:939745556996:android:a86036dca601d6b6531351',
    messagingSenderId: '939745556996',
    projectId: 'dlgrijpah7jlvfjuexnmcmv4p0rmbc',
    storageBucket: 'dlgrijpah7jlvfjuexnmcmv4p0rmbc.firebasestorage.app',
  );

}